name: 'Workflow of Child REPO'

on:
  push:
    branches: [ main, dev ]

jobs: 
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ssh-key: ${{secrets.CHILD_COMMIT_KEY}}

      - name: Trigger parent repo workflow
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{secrets.PARENT_TOKEN}}" \
            -d '{"ref":"main"}' \
            https://api.github.com/repos/JordanKikleo/parent_repo/actions/workflows/main_workflow.yml/dispatches