name: 'Workflow of Child REPO'

on:
  push:
    branches:
      - main 

jobs: 
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Workflow name
        shell: bash
        run: |
          echo "I am Workflow of Child REPO"
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.COMMIT_KEY }}'

      - name: Trigger parent repo workflow
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: JordanKikleo
          repo: parent_repo
          github_token: ${{ secrets.COMMIT_KEY }}
          workflow_file_name: main_workflow.yml
          ref: main
          wait_interval: 10
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
