name: 'Workflow of Child REPO'

on:
  push:
    branches:
      - main 

jobs: 
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ssh-key: ${{secrets.CHILD_COMMIT_KEY}}

      - name: Trigger parent repo workflow
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: JordanKikleo
          repo: parent_repo
          github_token: ${{ secrets.PARENT_COMMIT_KEY }}
          workflow_file_name: main_workflow.yml
          ref: main
          wait_interval: 10
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
